<?php

// This file was generated by the easy-wi.com installer

$host = 'localhost';
$user = 'deevs_main';
$db = 'deevs_main';
$pwd = '7zrNAviC7H?@';
$captcha = '0';
$title = 'Teste';
$debug = '0';
$timezone = 'UTC';
$coloreddashboard = false;
$easywitweets = false;
$examplemodule = false;
$debug = true;
